name: Build

on:
  push:
    branches: ["master"]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: bsdtar tree debootstrap jq binfmt-support u-boot-tools
          version: 1.0
      - run: make build_alpine=y build
      - run: tree .
      - uses: actions/upload-artifact@v4
        with:
          name: alpine
          path: tmp/rootfs.img
